### ISSUE TITLE
Can't open GitExtensions instance via the GitExt VS extension from project properties window

### ISSUE THREAD

**Issue by alkaberov** [gitextensions/gitextensions.vsix#15] opened 2020-11-08 11:43 UTC
Sequence:

1. Open project properties.
2. Try to open GitExtensions instance via folder image (GitExt VS extension) in my tool panel.
3. Get exception shown below.

![GitExt exception](https://user-images.githubusercontent.com/32940154/98463944-4f2a0480-21d0-11eb-9a37-6cbcbd757a84.jpg)

If I close project properties window this button working correctly.

This repositry has only two projects (main and test project), without complex structure or submodules or so on.

**Comment by gerhardol** [comment] 2020-11-08 18:44
Duplicate of #4

**Closed by gerhardol** 2020-11-08 18:44 UTC
